### ISSUE TITLE
Desktop Layout

### ISSUE THREAD

**Issue by lkk95** [lkk95/plateplan2.0#3]
## User Story
- As a user 
- I want to have a layout that fits my desktop
- so that I can use the app on my larger devices

## AC
* responsive header
* responsive footer

## Tasks
- [ ] create new branch
- [ ] create layout component
- [ ] create header component
- [ ] create footer component
- [ ] integrate header and footer in layout

## Complexity
small

## Linked to issue
