### ISSUE TITLE
Mobile Layout

### ISSUE THREAD

**Issue by lkk95** [lkk95/plateplan2.0#4]
## User Story
- As a user 
- I want to have a layout that fits my phone
- so that I can use the app on my phone

## AC
* responsive header
* responsive footer

## Tasks
- [ ] create new branch
- [ ] create layout component
- [ ] create header component
- [ ] create footer component
- [ ] integrate header and footer in layout

## Complexity
small

## Linked to issue
#3
